"""Render Markdown as portable, inline-styled HTML with a rich-text clipboard."""

import re
from html import escape
from urllib.parse import urljoin

from markdown_it import MarkdownIt

STYLES = {
    "p": "margin:18px 0;line-height:1.85;font-size:16px;color:#273244;overflow-wrap:anywhere;",
    "h1": "font-size:24px;margin:30px 0 18px;line-height:1.5;color:#14283f;",
    "h2": "font-size:21px;margin:32px 0 16px;line-height:1.5;color:#14283f;border-left:4px solid #2563eb;padding-left:12px;",
    "h3": "font-size:18px;margin:26px 0 12px;color:#14283f;",
    "strong": "font-weight:700;color:#14283f;",
    "a": "color:#2563eb;text-decoration:underline;overflow-wrap:anywhere;",
    "table": "border-collapse:collapse;width:100%;margin:20px 0;font-size:14px;table-layout:fixed;",
    "th": "background:#eef3fa;border:1px solid #cbd5e1;padding:10px 8px;text-align:left;line-height:1.6;overflow-wrap:anywhere;",
    "td": "border:1px solid #cbd5e1;padding:10px 8px;text-align:left;line-height:1.6;overflow-wrap:anywhere;",
    "blockquote": "margin:20px 0;padding:2px 16px;border-left:3px solid #94a3b8;background:#f4f6fa;",
    "ul": "padding-left:24px;margin:18px 0;",
    "ol": "padding-left:24px;margin:18px 0;",
    "li": "margin:8px 0;line-height:1.85;font-size:16px;",
    "hr": "border:0;border-top:1px solid #dbe3ee;margin:30px 0;",
    "code": "font-family:monospace;background:#f1f5f9;padding:2px 4px;overflow-wrap:anywhere;",
    "pre": "white-space:pre-wrap;overflow-wrap:anywhere;background:#f1f5f9;padding:16px;font-size:13px;line-height:1.6;",
    "img": "max-width:100%;height:auto;display:block;margin:20px auto;",
}


CAPTION_STYLE = "margin:8px 0 22px;line-height:1.65;font-size:13px;color:#6b7280;text-align:center;overflow-wrap:anywhere;"


def render(markdown, image_base_url="", image_urls=None):
    md = MarkdownIt("commonmark", {"html": False}).enable("table")
    tokens = md.parse(markdown)
    for index, token in enumerate(tokens):
        if token.type == "paragraph_open" and index + 1 < len(tokens):
            inline = tokens[index + 1]
            if (
                index >= 2
                and tokens[index - 2].type == "inline"
                and any(c.type == "image" for c in tokens[index - 2].children or [])
                and re.match(r"^\*?(?:图\s*\d+|自绘示意)[：:]", inline.content.strip())
            ):
                token.attrSet("data-figure-caption", "true")
        for child in token.children or []:
            if child.type == "image":
                source = child.attrGet("src") or ""
                if image_urls and source in image_urls:
                    child.attrSet("src", image_urls[source])
                elif image_base_url:
                    child.attrSet("src", urljoin(image_base_url, source))
    html = md.renderer.render(tokens, md.options, {})

    # Tags are generated by MarkdownIt; user-provided raw HTML is escaped.
    def inline_style(match):
        tag, attributes = match.groups()
        if tag not in STYLES:
            return match[0]
        is_caption = tag == "p" and "data-figure-caption" in attributes
        style = CAPTION_STYLE if is_caption else STYLES[tag]
        return f'<{tag} style="{style}"{attributes}>'

    return re.sub(r"<([a-z][a-z0-9]*)(\s[^>]*|)>", inline_style, html)


def preview(
    markdown,
    download_url="article.md",
    notes_url="paper-notes.md",
    image_base_url="",
    images_url="",
    image_urls=None,
):
    lines = markdown.splitlines()
    title = lines[0][2:].strip() if lines and lines[0].startswith("# ") else "技术文章"
    body = "\n".join(lines[1:]) if lines and lines[0].startswith("# ") else markdown
    article = render(body, image_base_url, image_urls)
    template = """<!doctype html><html lang="zh-CN"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1"><title>__TITLE__ · 公众号预览</title>
<style>body{margin:0;background:#edf1f6;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","Microsoft YaHei",sans-serif}header{padding:18px 24px;background:white;border-bottom:1px solid #dbe3ee}nav{display:flex;gap:10px;flex-wrap:wrap;align-items:center}button,.download{border:1px solid #cbd5e1;border-radius:7px;background:white;color:#273244;padding:10px 14px;font-size:14px;cursor:pointer;text-decoration:none}#copy{background:#2563eb;color:white;border-color:#2563eb}.hint,#status{font-size:13px;color:#526175;line-height:1.7}main{max-width:680px;margin:28px auto;background:white;padding:36px 40px;box-shadow:0 6px 30px #14283f0b}h1#title{font-size:28px;line-height:1.5;color:#14283f;margin:0 0 24px;overflow-wrap:anywhere}@media(max-width:740px){header{padding:14px}main{margin:16px 10px;padding:24px 18px}h1#title{font-size:25px}}</style></head>
<body><header><nav><button id="copy">复制正文到公众号</button><button id="copy-title">复制标题</button><a class="download" href="__DOWNLOAD__" download>下载 Markdown</a><a class="download" href="__NOTES__">查看证据笔记</a>__IMAGES__</nav><p class="hint">复制正文后，粘贴到公众号正文编辑区；标题请单独复制。图片会嵌入复制内容；若公众号未保留图片，请下载图片包按图注顺序上传。公众号编辑器可能调整排版。</p><p id="status" role="status">正文预览</p></header><main><h1 id="title">__TITLE__</h1><section id="article" style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI','Microsoft YaHei',sans-serif;color:#273244;line-height:1.85;max-width:100%;">__ARTICLE__</section></main>
<script>
const status = document.getElementById('status');
async function copyRich() {
 const node = document.getElementById('article'), clone = node.cloneNode(true), plain = node.innerText;
 status.textContent='正在准备正文与图片…';
 await Promise.all(Array.from(clone.querySelectorAll('img')).map(async img=>{
  const url=new URL(img.getAttribute('src'),document.baseURI);
  if(url.protocol==='data:') return;
  if(url.origin!==location.origin) throw new Error('外部图片无法可靠嵌入，请先保存到本地文章目录。');
  const response=await fetch(url.href); if(!response.ok) throw new Error('图片加载失败，请刷新后重试。');
  const blob=await response.blob(); if(!blob.type.startsWith('image/')) throw new Error('图片文件格式无效。');
  img.src=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(blob);});
 }));
 const html = clone.outerHTML;
 try {
  if (!navigator.clipboard || !window.ClipboardItem) throw new Error('fallback');
  await navigator.clipboard.write([new ClipboardItem({'text/html':new Blob([html],{type:'text/html'}),'text/plain':new Blob([plain],{type:'text/plain'})})]);
 } catch (error) {
  const selection = window.getSelection(), saved = [];
  for(let i=0;i<selection.rangeCount;i++) saved.push(selection.getRangeAt(i).cloneRange());
  const range = document.createRange(); range.selectNodeContents(node); selection.removeAllRanges(); selection.addRange(range);
  const handler = event => {event.preventDefault();event.clipboardData.setData('text/html',html);event.clipboardData.setData('text/plain',plain);};
  document.addEventListener('copy', handler);
  let success;
  try {success = document.execCommand('copy');} finally {document.removeEventListener('copy',handler);selection.removeAllRanges();saved.forEach(r=>selection.addRange(r));}
  if(!success) throw new Error('复制失败，请在浏览器中打开页面后重试。');
 }
 status.textContent=clone.querySelector('img')?'正文与图片已复制。粘贴后请检查图片；若图片未保留，请下载图片包上传。':'正文已复制，请粘贴到公众号正文编辑区。';
}
document.getElementById('copy').onclick=()=>copyRich().catch(e=>status.textContent=e.message);
document.getElementById('copy-title').onclick=async()=>{try{await navigator.clipboard.writeText(document.getElementById('title').textContent);status.textContent='标题已复制。';}catch(e){status.textContent='标题复制失败，请手动选择标题复制。';}};
</script></body></html>"""
    return (
        template.replace("__TITLE__", escape(title))
        .replace("__DOWNLOAD__", escape(download_url, quote=True))
        .replace("__NOTES__", escape(notes_url, quote=True))
        .replace(
            "__IMAGES__",
            f'<a class="download" href="{escape(images_url, quote=True)}" download>下载图片包</a>'
            if images_url
            else "",
        )
        .replace("__ARTICLE__", article)
    )
